import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  AuthProvider from '@/providers/AuthProvider';
import StoreProvider from "@/providers/StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FikraLabs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
          {children}
          </AuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
